version: '3'
services:
  service-tfm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - microservices
networks:
  microservices:
    name: microservices
